---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: john-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
        app: john
  template:
    metadata:
      labels:
        app: john
    spec:
      containers:
      - name: john
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80