---
apiVersion: v1
kind: Service
metadata:
  name: john-svc
  labels:
    app: john
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: john